application: xxxx
version: 1
runtime: go
api_version: go1
env_variables:
    MY_NAME: 'Cesar'
    MY_CAR: 'BMW'

handlers:
- url: /.*
  script: _go_app
  
error_handlers:
  - file: default_error.html
